<#
========================================================================================
COM5411 Enterprise Operating Systems – BarmBuzz
Run-BarmBuzz.ps1  (STUDENT REPO – “Gold Standard” Orchestrator)

YOU RUN ONE COMMAND:
    .\Run-BarmBuzz.ps1

YOU EDIT ONLY TWO FILES:
    1) DSC\Configurations\StudentConfig.ps1
    2) DSC\Data\AllNodes.psd1

EVERYTHING ELSE IS TUTOR-PROVIDED OR EVIDENCE OUTPUT.

WHY THIS SCRIPT EXISTS:
    - You are not expected to remember 30 PowerShell/DSC commands.
    - You are expected to prove YOUR work via repeatable builds and Git evidence.
    - This script enforces a predictable pipeline and produces evidence automatically.

WHAT THIS SCRIPT DOES (PIPELINE ORDER):
    Phase 0: Safety + Evidence
        - Checks you ran PowerShell as Administrator
        - Confirms required repo files exist
        - Creates Evidence\ folders if missing
        - Starts a transcript (Evidence\Transcripts\...)

    Phase 1: Prerequisites (tutor-provided)
        - Runs: Scripts\Prereqs\BarmBuzz_OneShot_LCM.ps1
        - This is where the tutor ensures DSC prerequisites are sane (LCM, modules, etc.)

    Phase 2: Compile + Apply DSC (YOUR WORK)
        - Loads data from: DSC\Data\AllNodes.psd1
        - Loads config from: DSC\Configurations\StudentConfig.ps1
        - Compiles DSC -> MOF files written to: DSC\Outputs\StudentBaseline\
        - Applies configuration to THIS machine (your VM)
        - Writes logs to Evidence\DSC\...

    Phase 3: Validation (later)
        - Placeholder for tutor-provided Pester tests (not implemented yet)

PASSWORD POLICY (FIXED FOR THIS LAB):
    - Local Windows Administrator password: superw1n_user
    - End-user password (for accounts you create later): notlob2k26

IMPORTANT:
    - DO NOT hardcode passwords in StudentConfig.ps1 or AllNodes.psd1
    - Week 1 does not require passwords inside DSC; it’s pipeline proof-of-life.
    - When we reach AD DS + user creation, the tutor will provide the credential mechanism.

EVIDENCE POLICY (ANTI-CONTRACT-CHEATING):
    - Outputs and Evidence are TRACKED IN GIT by design:
        * DSC\Outputs\
        * Evidence\
    - After each successful run:
        git add DSC\Outputs Evidence
        git commit -m "WeekX: <what changed>"

COMMON STUDENT FAILURE MODES THIS SCRIPT PREVENTS:
    - Running in the wrong folder -> script uses repo-relative paths only
    - Forgetting to create Evidence/ folders -> script creates them
    - Not capturing evidence -> transcript + logs are automatic
    - Random command soup -> one pipeline, one entrypoint

========================================================================================
#>

[CmdletBinding()]
param(
    # If you double-click this file and the window closes immediately, re-run with -Pause
    [switch]$Pause
)

# =============================================================================
# PHASE 0: SAFETY SETTINGS (FAIL FAST)
# =============================================================================
# StrictMode prevents use of uninitialised variables (common beginner bug).
Set-StrictMode -Version Latest

# Stop on first error (prevents “cascade failure” where you get 50 nonsense errors).
$ErrorActionPreference = "Stop"

# =============================================================================
# PHASE 0: PATHS (RELATIVE PATHS ONLY)
# =============================================================================
# Repo root folder is ALWAYS where this script lives.
$RootPath = $PSScriptRoot

# Tutor-provided scripts
$PrereqScript = Join-Path $RootPath "Scripts\Prereqs\BarmBuzz_OneShot_LCM.ps1"
$NetworkScript = Join-Path $RootPath "Scripts\Prereqs\BarmBuzz_OneShot_Network.ps1"

# Student-owned inputs (YOU edit these)
$StudentConfigScript = Join-Path $RootPath "DSC\Configurations\StudentConfig.ps1"
$StudentDataFile     = Join-Path $RootPath "DSC\Data\AllNodes.psd1"

# Outputs (generated by compilation, tracked in Git)
$OutputsRoot = Join-Path $RootPath "DSC\Outputs"

# Evidence (generated by runs, tracked in Git)
$EvidenceRoot = Join-Path $RootPath "Evidence"

# Fixed configuration name (YOU must define this in StudentConfig.ps1)
$ConfigName = "StudentBaseline"

# Idempotency: flag files to track if prereqs have already run
$LcmFlagFile = Join-Path $EvidenceRoot "prereq_lcm_complete.flag"
$NetworkFlagFile = Join-Path $EvidenceRoot "prereq_network_complete.flag"

# =============================================================================
# HELPER: create folders if missing
# =============================================================================
function New-FolderIfMissing {
    param([Parameter(Mandatory)][string]$Path)
    if (-not (Test-Path $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

# =============================================================================
# HELPER: admin check
# =============================================================================
function Assert-Admin {
    # DSC apply and (later) AD DS promotion require admin privileges.
    $principal = [Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw "You must run PowerShell as Administrator. (Start menu -> PowerShell -> Right-click -> Run as Administrator)"
    }
}

# =============================================================================
# HELPER: minimal schema check for AllNodes.psd1
# =============================================================================
function Assert-AllNodesData {
    param([Parameter(Mandatory)]$ConfigData)

    if (-not ($ConfigData -is [hashtable])) {
        throw "AllNodes.psd1 must return a hashtable. Example: @{ AllNodes = @( @{ NodeName='localhost' } ) }"
    }
    if (-not $ConfigData.ContainsKey("AllNodes")) {
        throw "AllNodes.psd1 must contain the key 'AllNodes'."
    }
    if (-not ($ConfigData.AllNodes -is [System.Array])) {
        throw "AllNodes must be an array: AllNodes = @( @{ NodeName='localhost' ... } )"
    }

    # For this module, we build on the local VM first, so we require localhost.
    $local = $ConfigData.AllNodes | Where-Object { $_.NodeName -eq "localhost" } | Select-Object -First 1
    if (-not $local) {
        throw "AllNodes must include NodeName = 'localhost' for this lab VM build."
    }
}

# =============================================================================
# CONSOLE BANNER (simple and obvious)
# =============================================================================
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "        COM5411 BarmBuzz Build Runner      " -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "[*] Repo root: $RootPath" -ForegroundColor Gray
Write-Host "[*] PowerShell: $($PSVersionTable.PSVersion)" -ForegroundColor Gray
Write-Host "[*] You edit ONLY: DSC\Configurations\StudentConfig.ps1 and DSC\Data\AllNodes.psd1" -ForegroundColor Gray

# =============================================================================
# PHASE 0: EVIDENCE FOLDERS (ALWAYS CREATE)
# =============================================================================
New-FolderIfMissing -Path $OutputsRoot
New-FolderIfMissing -Path $EvidenceRoot
New-FolderIfMissing -Path (Join-Path $EvidenceRoot "Transcripts")
New-FolderIfMissing -Path (Join-Path $EvidenceRoot "DSC")
New-FolderIfMissing -Path (Join-Path $EvidenceRoot "Network")
New-FolderIfMissing -Path (Join-Path $EvidenceRoot "AI_LOG")
New-FolderIfMissing -Path (Join-Path $EvidenceRoot "Git\Reflog")

# =============================================================================
# PHASE 0: START TRANSCRIPT (EVIDENCE)
# =============================================================================
$RunStamp = Get-Date -Format "yyyyMMdd_HHmmss"
$TranscriptPath = Join-Path $EvidenceRoot ("Transcripts\{0}_Run-BarmBuzz.txt" -f $RunStamp)

Start-Transcript -Path $TranscriptPath -Force | Out-Null
Write-Host "[+] Transcript started: Evidence\Transcripts\$(Split-Path -Leaf $TranscriptPath)" -ForegroundColor Green

try {
    # =========================================================================
    # PHASE 0: ADMIN CHECK
    # =========================================================================
    Assert-Admin
    Write-Host "[+] Admin privileges confirmed." -ForegroundColor Green

    # =========================================================================
    # PHASE 0: REQUIRED FILE CHECKS (FRIENDLY FAILURES)
    # =========================================================================
    if (-not (Test-Path $StudentConfigScript)) {
        throw "Missing: DSC\Configurations\StudentConfig.ps1 (this is one of the TWO files you must edit)."
    }
    if (-not (Test-Path $StudentDataFile)) {
        throw "Missing: DSC\Data\AllNodes.psd1 (this is one of the TWO files you must edit)."
    }
    if (-not (Test-Path $PrereqScript)) {
        throw "Missing tutor prereq script: Scripts\Prereqs\BarmBuzz_OneShot_LCM.ps1"
    }
    if (-not (Test-Path $NetworkScript)) {
        throw "Missing tutor prereq script: Scripts\Prereqs\BarmBuzz_OneShot_Network.ps1"
    }

    # =========================================================================
    # PHASE 1: PREREQUISITES (TUTOR-PROVIDED)
    # =========================================================================
    Write-Host "`n[Phase 1] Prerequisites..." -ForegroundColor Yellow
    
    # LCM Configuration (run only once)
    if (Test-Path $LcmFlagFile) {
        Write-Host "[*] LCM already configured (skipping)." -ForegroundColor Gray
    } else {
        & $PrereqScript
        New-Item -Path $LcmFlagFile -ItemType File -Force | Out-Null
        Write-Host "[+] LCM configured and flagged." -ForegroundColor Green
    }
    
    # Network Configuration (run only once)
    if (Test-Path $NetworkFlagFile) {
        Write-Host "[*] Network already configured (skipping)." -ForegroundColor Gray
    } else {
        & $NetworkScript
        New-Item -Path $NetworkFlagFile -ItemType File -Force | Out-Null
        Write-Host "[+] Network configured and flagged." -ForegroundColor Green
    }
    
    Write-Host "[+] Phase 1 complete." -ForegroundColor Green

    # =========================================================================
    # PHASE 2: COMPILE + APPLY DSC (YOUR WORK)
    # =========================================================================
    Write-Host "`n[Phase 2] Compile + Apply DSC..." -ForegroundColor Yellow

    # 2.1 Load the configuration data
    $ConfigData = Import-PowerShellDataFile -Path $StudentDataFile
    Assert-AllNodesData -ConfigData $ConfigData
    Write-Host "[+] Loaded AllNodes configuration data." -ForegroundColor Green

    # 2.2 Load the student configuration script
    # Dot-sourcing makes the Configuration definition available in this session.
    . $StudentConfigScript
    Write-Host "[+] Loaded StudentConfig.ps1." -ForegroundColor Green

    # 2.3 Confirm the required configuration exists
    if (-not (Get-Command $ConfigName -ErrorAction SilentlyContinue)) {
        throw "StudentConfig.ps1 must define a Configuration named '$ConfigName'. Check spelling and naming."
    }
    Write-Host "[+] Found configuration: $ConfigName" -ForegroundColor Green

    # 2.4 Compile output path (MOF generation destination)
    $CompileOut = Join-Path $OutputsRoot $ConfigName
    New-FolderIfMissing -Path $CompileOut

    Write-Host "[*] Compiling -> DSC\Outputs\$ConfigName" -ForegroundColor Gray

    # IMPORTANT:
    # This call compiles your configuration into MOF files.
    # The result should be a file like:
    #   DSC\Outputs\StudentBaseline\localhost.mof
    & $ConfigName -ConfigurationData $ConfigData -OutputPath $CompileOut

    Write-Host "[+] Compilation complete." -ForegroundColor Green

    # Evidence: record what was compiled
    Get-ChildItem -Path $CompileOut -Recurse |
        Select-Object FullName, Length, LastWriteTime |
        Out-File (Join-Path $EvidenceRoot ("DSC\{0}_compiled_files.txt" -f $RunStamp)) -Encoding UTF8

    # 2.5 Apply configuration
    Write-Host "[*] Applying configuration (waits until complete)..." -ForegroundColor Gray

    Start-DscConfiguration -Path $CompileOut -Wait -Force -Verbose 4>&1 |
        Tee-Object -FilePath (Join-Path $EvidenceRoot ("DSC\{0}_apply_verbose.txt" -f $RunStamp))

    Write-Host "[+] Apply complete." -ForegroundColor Green

    # Evidence: quick network/time diagnostics (these solve 60% of lab issues)
    ipconfig /all | Out-File (Join-Path $EvidenceRoot ("Network\{0}_ipconfig.txt" -f $RunStamp)) -Encoding UTF8
    w32tm /query /status 2>&1 | Out-File (Join-Path $EvidenceRoot ("Network\{0}_w32tm_status.txt" -f $RunStamp)) -Encoding UTF8

    # =========================================================================
    # PHASE 3: VALIDATION (PLACEHOLDER)
    # =========================================================================
    Write-Host "`n[Phase 3] Validation..." -ForegroundColor Yellow
    Write-Host "[*] Pester validation will be added here by the tutor later." -ForegroundColor Gray

    # =========================================================================
    # END: SUCCESS MESSAGE + EXACT GIT COMMANDS
    # =========================================================================
    Write-Host "`n[+] BUILD SUCCESS" -ForegroundColor Green
    Write-Host "[*] Next steps (you MUST commit outputs + evidence):" -ForegroundColor Gray
    Write-Host "    git add DSC\Outputs Evidence" -ForegroundColor Gray
    Write-Host "    git commit -m ""Build $RunStamp""" -ForegroundColor Gray
}
catch {
    Write-Host "`n[-] BUILD FAILED" -ForegroundColor Red
    Write-Host ("Message: {0}" -f $_.Exception.Message) -ForegroundColor Red

    if ($_.ScriptStackTrace) {
        Write-Host "`nStackTrace:" -ForegroundColor DarkRed
        Write-Host $_.ScriptStackTrace -ForegroundColor DarkRed
    }

    try { Stop-Transcript | Out-Null } catch { }
    exit 1
}
finally {
    try { Stop-Transcript | Out-Null } catch { }
    if ($Pause) { Read-Host -Prompt "Press Enter to exit" | Out-Null }
}

<#
========================================================================================
APPENDIX: WHAT YOUR TWO STUDENT FILES SHOULD LOOK LIKE (MINIMAL EXAMPLES)

1) DSC\Data\AllNodes.psd1
--------------------------------
@{
    AllNodes = @(
        @{
            NodeName   = 'localhost'
            Role       = 'DC'
            DomainName = 'bolton.barmbuzz.test'
        }
    )
}

2) DSC\Configurations\StudentConfig.ps1
----------------------------------------
Configuration StudentBaseline {
    param()

    Import-DscResource -ModuleName PSDesiredStateConfiguration

    Node $AllNodes.NodeName {

        # Week 1 proof-of-life example:
        File ProofOfLife {
            DestinationPath = 'C:\BarmBuzz-ProofOfLife.txt'
            Contents        = 'Hello from DSC'
            Type            = 'File'
            Ensure          = 'Present'
        }
    }
}

If the proof-of-life works, then your pipeline works.
Then you extend from File -> WindowsFeature -> AD DS -> OUs -> Users -> Groups -> GPO.

========================================================================================
#>
